### ISSUE TITLE
presets: move profile and profileLevel fields to video json object

### ISSUE THREAD

**Issue by flavioribeiro** [NYTimes/video-transcoding-api#125]
profile and profileLevel fields should be related to video, we should move them to the video object.

**Comment by fsouza** [comment]
Closing from b17749f8aa423a3164de32f81ea570b9c725654d (for some reason github didn't catch this one).

**Comment by fsouza** [comment]
Reopening, Github didn't catch it because b17749f8aa423a3164de32f81ea570b9c725654d isn't merged.

<img src="https://d262ilb51hltx0.cloudfront.net/max/455/1*snTXFElFuQLSFDnvZKJ6IA.png">
