### ISSUE TITLE
provider/zencoder: getting an error when trying to trigger encoding job with no height or no width

### ISSUE THREAD

**Issue by goldsteindavid** [NYTimes/video-transcoding-api#148]
When running a zencoder job for a webm file using a preset that has no height or no width specified I get the following error:

``` JSON
{
  "error": "Error with provider \"zencoder\": 422 Unprocessable Entity"
}
```

**Comment by goldsteindavid** [comment]
After receiving the above error I started to get another when trying to post a zencoder preset with no height or no width. (Note: I was able to post these presets before I got the original error I wrote this ticket about.)
`{
  "PresetMap": "", 
  "Results": {
    "zencoder": {
      "Error": "creating preset: local preset already exists", 
      "PresetID": ""
    }
  }
}`

Here is my preset JSON:
`{
  "providers": ["zencoder"],
  "preset": {
    "name": "QA_zencoder_webm_vbr_noheight",
    "description": "preset_zencoder_webm_vbr_noheight for QA.",
    "container": "webm",
    "rateControl": "VBR",
    "video": {
      "profile": "Main",
      "profileLevel": "3.1",
      "height": "",
      "width": "1080",
      "codec": "vp8",
      "bitrate": "1000000",
      "gopSize": "90",
      "gopMode": "fixed",
      "interlaceMode": "progressive"
    },
    "audio": {
        "codec": "vorbis",
        "bitrate": "64000"
    }
  },
  "outputOptions": {
    "label": "webm_720p"
  }
}
`

**Comment by flavioribeiro** [comment]
Hello @goldsteindavid I tried to reproduce this one with no success.

```
flv@~/Development/video-transcoding-api-examples cat preset_david.json
```

```json
{
  "providers": ["zencoder"],
  "preset": {
    "name": "QA_zencoder_webm_vbr_noheight",
    "description": "preset_zencoder_webm_vbr_noheight for QA.",
    "container": "webm",
    "rateControl": "VBR",
    "video": {
      "profile": "Main",
      "profileLevel": "3.1",
      "height": "",
      "width": "1080",
      "codec": "vp8",
      "bitrate": "1000000",
      "gopSize": "90",
      "gopMode": "fixed",
      "interlaceMode": "progressive"
    },
    "audio": {
        "codec": "vorbis",
        "bitrate": "64000"
    }
  },
  "outputOptions": {
    "label": "webm_720p"
  }
}
```
and

```
flv@~/Development/video-transcoding-api-examples cat job.json
```
```json
{
  "provider": "zencoder",
  "source": "https://nyt-video-tests.s3.amazonaws.com/animation_sorkin_mezz.mov",
  "outputs": [
    {"preset": "QA_zencoder_webm_vbr_noheight", "fileName": "output_david.webm"}
  ]
}
```
Triggering the job:
```
flv@~/Development/video-transcoding-api-examples curl -X POST -d @job.json http://localhost:8080/jobs
```
```json
{"jobId":"7d3be3133c4dd4b8"}
```

I checked the output and things are good. Am I missing something?

**Comment by flavioribeiro** [comment]
also, this:

```json
{
  "PresetMap": "", 
  "Results": {
    "zencoder": {
      "Error": "creating preset: local preset already exists", 
      "PresetID": ""
    }
  }
}
```

happens when you [remove the presetmap](https://github.com/NYTimes/video-transcoding-api/wiki/Using-Video-Transcoding-API#deleting-presetmap) but don't [remove the preset](https://github.com/NYTimes/video-transcoding-api/wiki/Using-Video-Transcoding-API#deleting-preset), which raises another question.

@marzagao, @fsouza: since we have the concept of `LocalPreset`s now, we can support all encoding services even if they don't have API's to handle presets. Do you guys think we should still expose PresetMaps?

**Comment by goldsteindavid** [comment]
I'm no longer able to reproduce this issue.
