### ISSUE TITLE
encoding.com and zencoder: difference in path node in JSON response for jobs endpoint

### ISSUE THREAD

**Issue by goldsteindavid** [NYTimes/video-transcoding-api#149]
encodingcom and zencoder are reporting different results for the path node in the JSON response for jobs endpoint. Encodingcom is giving the s3 path while zencoder is giving the http path. 

For Example (bucketname, jobId and filename are placeholders):
Encoding: s3://access_key:secret_access@bucketname/jobId/filename

Zencoder: http://bucketname.s3.amazonaws.com/bucketname/jobId/filename

**Comment by flavioribeiro** [comment]
@fsouza, @marzagao   I'm wondering if this will affect how the distribution step works on our internal deployment. Do you think we should normalize this?

**Comment by flavioribeiro** [comment]
I think we're having problems on the distribution step due to this issue. I will address it right now.
