### ISSUE TITLE
provider/encodingcom: preset creation is failing

### ISSUE THREAD

**Issue by fsouza** [NYTimes/video-transcoding-api#167]
This is probably due to #159. We get the following error:

```
creating preset: Error returned by the Encoding.com API: {\"Errors\":[\"Validation Destination is required for this format (format #0)\"]}
```

**Comment by marzagao** [comment]
Definitively, I remember now. I knew there was a reason why I had kept that in there. I had tested job creation before merging that PR but didn't test preset creation. Should we just revert #159?

**Comment by flavioribeiro** [comment]
yeah maybe we should revert but it would be good to have docs for that line.. maybe just a link to this issue :)

**Comment by marzagao** [comment]
Ok, will do!
