### ISSUE TITLE
providers: add support for mediaconvert

### ISSUE THREAD

**Issue by flavioribeiro** [nytimes/video-transcoding-api#194]
AWS seems to be discontinuing Elastic Transcoder in favor of [MediaConvert](https://aws.amazon.com/mediaconvert/). It would be great to see MediaConvert support on this API.

**Comment by dictcp** [comment]
there is an wip branch on it at https://github.com/dictcp/video-transcoding-api/tree/provider/mediaconvert.
stay tuned.
